AllCops:
  TargetRubyVersion: 3.1.3
  NewCops: enable

require:
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-performance

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

RSpec/NestedGroups:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*.rb"

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ContextWording:
  Enabled: false