default: &default
  base_url: "localhost:3050"

  # In seconds.
  temporary_block_duration: 600

  app_name: "La Porta D'acqua"
  # admin_name: AdminName
  # admin_email: admin@email.net
  # user_block_ttl: 600
  # base_url: "http://localhost:3050"
  frontend_base_url: "http://localhost:4250"
  reset_password_url: "{{frontend_base_url}}/#/auth/reset-password/{{token}}"
  # mail_attachment_max_size: 25 MB

  root_duration: 600 # 5 minutes

  max_login_attempts: 10

  emails:
    default_from: no-reply@example.com

  # 'cr' stands for 'cancel reservation'
  cancel_reservation_path: "/#/cr/{{secret}}"

  # Basic page where you can see your reservations details.
  # 'r' stands for 'reservation'
  show_reservation_url: "{{frontend_base_url}}/#/r/{{secret}}"

  # When user cancels reservation payment, will be sent here:
  cancelled_payment_reservation_url: "{{frontend_base_url}}/#/r/{{secret}}/cancelled"

  # After user completed payment, will be sent here:
  processed_payment_reservation_url: "{{frontend_base_url}}/#/r/{{secret}}/processed"

  nexi_hpp_payment_path: api/phoenix-0.0/psp/api/v1/orders/hpp

  nexi_api_url: https://xpaysandbox.nexigroup.com

  # ---------------------------------------------------------
  # SMTP CONFIGURATIONS
  # ---------------------------------------------------------
  # You can set SMTP configurations for email delivery here.
  #
  # address:              | Specify the host (hostname or IP) of mail server
  #                       | to which mail client have to connect to deliver emails.
  # port:                 | SMTP port number on mail server.
  # domain:               | Domain name for which we're going to deliver emails. Usually it
  #                       | matches the last part of email address (admin@example.com -> example.com).
  # enable_starttls_auto: | Enable automatic STARTTLS configuration detection and automatic protocol switch.
  # openssl_verify_mode:  | Specify server SSL certificate verification mode ('none' to disable).
  # authentication:       | Specify the type of SMTP authentication to use (set to null when disabled)
  # user_name:            | Username to use for SMTP authentication (used when authentication is specified)
  # password:             | The password of SMTP user
  #
  # Example:
  #
  # smtp:
  #   address: mail.example.com
  #   port: 587
  #   domain: example.com
  #   enable_starttls_auto: true
  #   openssl_verify_mode: none
  #   authentication: plain
  #   user_name: user@example.com
  #   password: mysecret
  #   open_timeout: 60
  #   read_timeout: 60

  # Email addresses where to send final email (when projects are closed)
  # final_project_emails:
  #  - sasha@opinioni.net

  # emails:
  #   default_from: no-reply@example.com
  #   default_reply_to: assistenza@opinioni.net

  # exceptions:
  #   enabled: false
  #   subject_prefix: "Quotations"
  #   sender: '"Exception" <exception@opinioni.net>'
  #   recipients:
  #     - "developers@opinioni.net"

  # finale_zip_password: password

  # developers_emails:
  #  - sasha@opinioni.net

  # send_developers_emails: true

  # async_actions_timeout: 10 minutes

  # # Seconds you can restore object after
  # restore_object_timeout: 3600

  smtp: null
  # origins:
  #   - localhost

  # https://thecatapi.com/signup
  cat_api_key: "<insert your cat api here>"

  cors_origins:
    - localhost
    - laportadacqua.com

  cookie_secure: true
  cookie_same_site: None

development:
  <<: *default

# NOTE: changing test configurations may cause errors when running tests.
test:
  <<: *default
  # mail_attachment_max_size: 25 MB
  cookie_secure: false
  cookie_same_site: "Lax"

  # Nexi sandbox api url
  nexi_api_url: https://xpaysandbox.nexigroup.com

production:
  <<: *default