default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { 'redis://localhost:6379/1' } %>
  channel_prefix: websocket

development:
  <<: *default

test:
  <<: *default
  url: "redis://localhost:6379/5"

production:
  <<: *default
