default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("LPDA2_DATABASE_HOST", nil) %>
  password: <%= ENV.fetch("LPDA2_DATABASE_PASSWORD", nil) %>
  user: <%= ENV.fetch("LPDA2_DATABASE_USERNAME", nil) %>

development:
  <<: *default
  database: lpda2_development

test:
  <<: *default
  database: lpda2_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: lpda2
