remind_reservations_mail_job:
  cron: "0 10 * * *"
  class: RemindReservationsMailJob
  queue: default

remind_reservation_payments_job:
  cron: "0 10 * * *"
  class: RemindReservationPaymentsJob
  queue: default

update_all_reservation_payment_status_job:
  cron: "0 * * * *"
  class: UpdateAllReservationPaymentStatusJob
  queue: default